// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO_iowrjHknCTHHBMt2flfY7aIzYgmwJg',
    appId: '1:711026821973:web:f303d22c7ef216eb5bbddc',
    messagingSenderId: '711026821973',
    projectId: 'db-cp-5ffd3',
    authDomain: 'db-cp-5ffd3.firebaseapp.com',
    storageBucket: 'db-cp-5ffd3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiVV-gHEpvz5w16boZm95df0VkBw6-KKE',
    appId: '1:711026821973:android:1bd3fab2b5d34ded5bbddc',
    messagingSenderId: '711026821973',
    projectId: 'db-cp-5ffd3',
    storageBucket: 'db-cp-5ffd3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9NYwqnT-QU2suX4Uv6q5JJIuvB4-j4Ms',
    appId: '1:711026821973:ios:b153611eb269da0c5bbddc',
    messagingSenderId: '711026821973',
    projectId: 'db-cp-5ffd3',
    storageBucket: 'db-cp-5ffd3.firebasestorage.app',
    iosBundleId: 'com.example.apsglam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9NYwqnT-QU2suX4Uv6q5JJIuvB4-j4Ms',
    appId: '1:711026821973:ios:b153611eb269da0c5bbddc',
    messagingSenderId: '711026821973',
    projectId: 'db-cp-5ffd3',
    storageBucket: 'db-cp-5ffd3.firebasestorage.app',
    iosBundleId: 'com.example.apsglam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDO_iowrjHknCTHHBMt2flfY7aIzYgmwJg',
    appId: '1:711026821973:web:a81b14de599ec4235bbddc',
    messagingSenderId: '711026821973',
    projectId: 'db-cp-5ffd3',
    authDomain: 'db-cp-5ffd3.firebaseapp.com',
    storageBucket: 'db-cp-5ffd3.firebasestorage.app',
  );
}
